name: jellyfin

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks: 
      - nginx_reverse_proxy_nginx
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ~/Syncthing/docker/.config/jellyfin/library:/config
      - ~/Syncthing/movies:/data/movies
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

networks:
  nginx_reverse_proxy_nginx:
    external: true