name: nextcloud

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    network_mode: nginx
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - ~/Syncthing/docker/.config/nextcloud/config:/config
      - ~/Syncthing/nextcloud:/data
    ports:
      - 8888:443
    restart: unless-stopped
