name: nextcloud

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ~/Syncthing/docker/.config/nextcloud/config:/config
      - ~/Syncthing:/data
    ports:
      - 8888:443
    restart: unless-stopped
