name: portainer

services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    network_mode: nginx
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/Syncthing/docker/.config/portainer/portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
    restart: unless-stopped