name: portainer

services:
  portainer:
    image: portainer/portainer-ce:2.21.5
    container_name: portainer
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.config/portainer/portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
    restart: unless-stopped