services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    network_mode: nginx
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      VERSION: 1.21.4
      MEMORY: 3G
      MODS: https://cdn.modrinth.com/data/P7dR8mSH/versions/8FAH9fuR/fabric-api-0.114.2%2B1.21.4.jar
      PLUGINS: https://cdn.modrinth.com/data/fALzjamp/versions/VkAgASL1/Chunky-Fabric-1.4.27.jar
      DIFFICULTY: hard
      ONLINE_MODE: "FALSE"
      RCON_CMDS_STARTUP: |-
        /chunky cancel
        /chunky confirm
        /chunky center spawn
        /chunky shape circle
        /chunky radius 50000
        /chunky start overworld
        /chunky start the_nether
        /chunky start the_end

      RCON_CMDS_FIRST_CONNECT: |-
        /chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        /chunky continue
      #OVERRIDE_SERVER_PROPERTIES: "FALSE"
      #SKIP_SERVER_PROPERTIES: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - C:\Users\max\Documents\server-mc:/data