name: uptime-kuma

services:
  portainer:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    networks: 
      - nginx_reverse_proxy_nginx
    volumes:
      - ~/Syncthing/docker/.config/uptime-kuma/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:3001:3001"
    restart: unless-stopped

networks:
  nginx_reverse_proxy_nginx:
    external: true