name: uptime-kuma

services:
  portainer:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    network_mode: nginx
    volumes:
      - ~/Syncthing/docker/.config/uptime-kuma/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped