name: vpn_stack

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    networks: 
      - nginx_reverse_proxy_nginx
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP=!!!!!!!!!!!!!!!!!
      - WIREGUARD_ENDPOINT_PORT=!!!!!!!!!!!!!!!!!
      - WIREGUARD_PUBLIC_KEY=!!!!!!!!!!!!!!!!!
      - WIREGUARD_PRIVATE_KEY=!!!!!!!!!!!!!!!!!
      - WIREGUARD_PRESHARED_KEY=!!!!!!!!!!!!!!!!!
      - WIREGUARD_ADDRESSES=!!!!!!!!!!!!!!!!!
    ports:
      - "127.0.0.1:8112:8112"
      - "127.0.0.1:6881:6881"
      - "127.0.0.1:6881:6881/udp"
    restart: unless-stopped
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Etc/UTC
    volumes:
      - ~/Syncthing/docker/.config/deluge/config:/config
      - ~/Syncthing/movies:/downloads

    network_mode: "service:gluetun"
    restart: unless-stopped

networks:
  nginx_reverse_proxy_nginx:
    external: true